name: sketch_arena
description: Sketch Arena is a multiplayer online game where players take turns drawing a given word while others try to guess it, scoring points for correct answers.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^7.0.1
  intl: ^0.18.0
  supabase_flutter: ^1.9.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
